### ISSUE TITLE
bundle.js loading under ./public/javascripts

### ISSUE THREAD

**Issue by thatrealdann** [HackaIran/HackaPanel#14]
Threw an err [Loading failed for the <script> with source “http://localhost:3000/javascripts/bundle.js”] occurred due to the lack of existence.

Expectation: 
![32375684-c67e4208-c0b7-11e7-8a97-e35fe3b0b072](https://user-images.githubusercontent.com/23521006/33255859-b184ae04-d364-11e7-85f8-a1bf50b65893.jpg)

Reality: 
![test](https://user-images.githubusercontent.com/23521006/33255934-fde7c1a0-d364-11e7-837a-0f43221a93cd.PNG)

Even more real:
![err](https://user-images.githubusercontent.com/23521006/33255788-63f983f8-d364-11e7-9043-f4a1e9c388fc.PNG)

**Comment by Alireza29675** [comment]
Hey Dani,

go to **_contest/_**, rename those three files and remove **_.sample_** in their name

### OR

[contest.zip](https://github.com/Alireza29675/HackaPanel/files/1505179/contest.zip)
Download this file and extract it into the **_contest/_** to reach "HackaKaraj2's challenge" as an example

**Comment by Alireza29675** [comment]
Also, you have to setup MongoDB on your PC and make a DB named "hacka"
you can set up and configure DB information and contest time in **_config/hacka.config.js_**

Let me know if this helped you
Thank you:)

**Comment by thatrealdann** [comment]
Well I got:
-  MongoDB installed, up and running "hacka" db.
- Contest folder is fastened and loaded.
- "hacka.config" points `db: {
        host: 'mongodb://127.0.0.1/',
        dbname: 'hacka'
    }`

which is the local mongodb server going on but silly me still having the same error! >.>

**Comment by Alireza29675** [comment]
@thatrealdann Don't worry it's a common testing phrase:D
but give me more information about these questions:
1. Do you use master branch?
2. Are DOM elements rendered? (are they just hidden or not rendered at all?)
3. Can you pull new commits and run `npm test` to see if everything's ok in _**contest/**_ folder?
I tested this, on some PCs, and all results were the same, I'll be glad if you check it more carefully and find what's wrong so we could fix it

**Comment by thatrealdann** [comment]
> Do you use master branch?

**Roger, that's the one I'm using.**


> Are DOM elements rendered? (are they just hidden or not rendered at all?)

![capture](https://user-images.githubusercontent.com/23521006/33361801-ed766e26-d4ee-11e7-8daf-eca464366492.PNG)


> Can you pull new commits and run npm test to see if everything's ok in contest/ folder?

![capture](https://user-images.githubusercontent.com/23521006/33362219-8ea5a900-d4f0-11e7-84e3-b8105b4df73f.PNG)

**Comment by Alireza29675** [comment]
@thatrealdann After doing above things, you have to do this to fix your bug:
1. install `webpack` globally using **npm** by running this command: `npm install -g webpack`
2. open terminal and go to HackaPanel path
3. run this command to make a js bundle file: `webpack`
4. reopen `127.0.0.1:3000`
