### ISSUE TITLE
Logout button is a need

### ISSUE THREAD

**Issue by EYazdpour** [HackaIran/HackaPanel#18]
There is no logout button in the panel; Having one can make a better user experience.

**Comment by shahabbasi** [comment]
Hi
We are using HackaPanel for contests which the login info will never be used afterwards and there is no need of logging out but if you need to switch the logged PC the way is to just closing the tab on the other one and try logging in with the new PC. HackaPanel understands that the other one is logged out.
By the way it would be a good help if you can do that with a pull request and we'll be happy.

**Comment by EYazdpour** [comment]
@shahabbasi  If you have a login form you SHOULD consider a way for people to logout or at least set a message for them to make it clear how they can logout of HackaPanel. It doesn't matter if you use it in a certain way because it's a general idea of how user experience should works!
By the way I'm trying my best to contribute as much as I can afford.

**Comment by Alireza29675** [comment]
@EYazdpour logout button has been made [here](https://github.com/HackaIran/HackaPanel/commit/06f29e02a9da6ae7ddc07ae5f8b94e79490be058)
Thumbs up for giving useful feedbacks!

**Comment by Alireza29675** [comment]
![screen shot 1397-05-08 at 9 02 08 pm](https://user-images.githubusercontent.com/2771377/43410366-e8c1001e-943b-11e8-8a2f-8573785ba08a.png)
And this is how the button looks like right now:)
